In [157]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [158]:
df_test = pd.read_csv("test_data.csv")
df_train = pd.read_csv("train_data.csv")

In [159]:
df_train.head()

,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,...,v30,v31,v32,v33,v34,v35,v36,v37,v38,v39
0,183048TW0006094,27-12-2017,3048,2524,ASC,49000,61.22,1016,16930.58,4.0,...,24,0,NaN,NaN,NaN,NaN,NaN,N,NO,7740.0
1,313035TW0012161,22-01-2018,3035,2118,DEALER,61990,78.08,1008,31564.74,3.0,...,24,0,NaN,NaN,NaN,NaN,NaN,N,NO,23340.0
2,313035TW0012394,21-12-2017,3035,4895,DEALER,47440,84.11,1016,28627.74,3.0,...,24,0,19135.0,27.0,38835.0,0.0,-50.0,N,NO,16980.0
3,223005TW0106272,31-12-2017,3005,3252,ASC,57810,84.89,1016,49684.70,0.0,...,25,0,NaN,NaN,NaN,NaN,NaN,N,NO,28920.0
4,183050TW0005062,31-12-2017,3050,2206,DEALER,49000,85.20,1016,40158.23,4.0,...,37,0,NaN,NaN,NaN,NaN,NaN,N,NO,21560.0

In [160]:
df_train.describe()

,v3,v6,v7,v8,v9,v10,v15,v16,v17,v18,...,v28,v29,v30,v31,v32,v33,v34,v35,v36,v39
count,115786.000000,115786.000000,115786.000000,115786.000000,115786.000000,115785.000000,115786.000000,115786.000000,115348.000000,115348.000000,...,115786.000000,115348.000000,115786.000000,115786.000000,8.333100e+04,83331.000000,8.333100e+04,83331.000000,83130.000000,115786.000000
mean,3033.212616,68055.756387,82.107888,1011.172750,47945.598106,4.253496,0.922797,2018.184521,17.526893,20.646895,...,20.749149,59.007201,30.311022,0.479782,5.763100e+05,5.225366,1.663438e+06,1.804035,1.434548,31005.473422
std,28.179073,19552.343137,6.476091,4.734627,21144.079226,3.859914,0.266914,1.337184,11.134717,11.115424,...,5.308833,39.709378,7.014841,0.499593,2.310622e+07,10.245461,3.826392e+07,1.326908,17.153316,12201.936885
min,3000.000000,27310.000000,0.000000,1000.000000,0.000000,-13.000000,0.000000,2011.000000,1.000000,2.000000,...,10.000000,2.083333,8.000000,0.000000,0.000000e+00,-26.000000,0.000000e+00,0.000000,-98.000000,830.000000
25%,3009.000000,55000.000000,79.250000,1008.000000,33019.192500,2.000000,1.000000,2017.000000,9.000000,13.000000,...,15.000000,33.333333,24.000000,0.000000,6.380000e+02,1.000000,2.834000e+03,1.000000,-8.000000,22000.000000
50%,3025.000000,65000.000000,83.720000,1009.000000,46481.000000,3.000000,1.000000,2018.000000,15.000000,19.000000,...,20.000000,51.428571,30.000000,0.000000,8.100000e+02,1.000000,7.520000e+03,2.000000,4.000000,29450.000000
75%,3051.000000,76000.000000,86.270000,1016.000000,60438.030000,4.000000,1.000000,2019.000000,23.000000,26.000000,...,25.000000,75.000000,36.000000,1.000000,2.790000e+03,4.000000,1.550000e+04,3.000000,12.000000,38493.000000
max,3111.000000,290200.000000,100.000000,1020.000000,231562.330000,37.000000,1.000000,2022.000000,129.000000,131.000000,...,30.000000,688.888889,82.000000,1.000000,1.000000e+09,114.000000,1.000000e+09,17.000000,50.000000,161080.000000

In [161]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115786 entries, 0 to 115785
Data columns (total 39 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   v1      115786 non-null  object
 1   v2      115348 non-null  object
 2   v3      115786 non-null  int64
 3   v4      115786 non-null  object
 4   v5      115786 non-null  object
 5   v6      115786 non-null  int64
 6   v7      115786 non-null  float64
 7   v8      115786 non-null  int64
 8   v9      115786 non-null  float64
 9   v10     115785 non-null  float64
 10  v11     93362 non-null   object
 11  v12     93362 non-null   object
 12  v13     93362 non-null   object
 13  v14     93362 non-null   object
 14  v15     115786 non-null  int64
 15  v16     115786 non-null  int64
 16  v17     115348 non-null  float64
 17  v18     115348 non-null  float64
 18  v19     108867 non-null  object
 19  v20     115786 non-null  int64
 20  v21     115786 non-null  int64
 21  v22     115786 non-null  int64
 22  v23     115786 non-null  int64
 23  v24     115348 non-null  float64
 24  v25     115786 non-null  int64
 25  v26     115786 non-null  int64
 26  v27     115786 non-null  int64
 27  v28     115786 non-null  int64
 28  v29     115348 non-null  float64
 29  v30     115786 non-null  int64
 30  v31     115786 non-null  int64
 31  v32     83331 non-null   float64
 32  v33     83331 non-null   float64
 33  v34     83331 non-null   float64
 34  v35     83331 non-null   float64
 35  v36     83130 non-null   float64
 36  v37     115786 non-null  object
 37  v38     115786 non-null  object
 38  v39     115786 non-null  float64
dtypes: float64(13), int64(15), object(11)
memory usage: 34.5+ MB

In [162]:
# Drop v1 ++
# convert v2 into, number of days since the vehicle has been seized ++
# v3,v4,v5 seem useless and can be dropped depending on the correlation with the target value ++
# v8 will have to a OHE as different models ++
# v10,v16,v23,v24 and what i want to do with v2 seem the same. PCA can be applied depending on the correlation ++
# v11,v12,v13,v14 can be averaged together to form a single value
# v17 and v18 seem the same, PCA 
# v19,v20 seem useless 
# v21,v22 seem the same 
# V26 seems useless

In [163]:
# len(df_train[df_train["v5"] == "ASC"])

In [164]:
# df_train["v38"].unique()

In [165]:
# df_train = df_train.drop({"v1","v2","v4","v3","v19"}, axis=1)

In [173]:
df_train = df_train.drop({"v1","v2","v4","v19"}, axis=1)

In [174]:
df_train.head()

,v3,v5,v6,v7,v8,v9,v10,v11,v12,v13,...,v30,v31,v32,v33,v34,v35,v36,v37,v38,v39
0,3048,1,49000,61.22,1016,16930.58,4.0,NaN,NaN,NaN,...,24,0,NaN,NaN,NaN,NaN,NaN,0,0,7740.0
1,3035,0,61990,78.08,1008,31564.74,3.0,NaN,NaN,NaN,...,24,0,NaN,NaN,NaN,NaN,NaN,0,0,23340.0
2,3035,0,47440,84.11,1016,28627.74,3.0,NaN,NaN,NaN,...,24,0,19135.0,27.0,38835.0,0.0,-50.0,0,0,16980.0
3,3005,1,57810,84.89,1016,49684.70,0.0,NaN,NaN,NaN,...,25,0,NaN,NaN,NaN,NaN,NaN,0,0,28920.0
4,3050,0,49000,85.20,1016,40158.23,4.0,NaN,NaN,NaN,...,37,0,NaN,NaN,NaN,NaN,NaN,0,0,21560.0

In [175]:
# Fixing categorical data 
cleanup_nums =     {"v5": {"ASC" : 1, "DEALER" : 0},
                    "v11": {"P": 0, "A": 1, "G": 2},
                    "v12": {"P": 0, "A": 1, "G": 2},
                    "v13": {"P": 0, "A": 1, "G": 2},
                    "v14": {"P": 0, "A": 1, "G": 2},
                    "v37": {"N": 0, "Y": 1},
                    "v38": {"NO": 0, "YES": 1}
                    }
df_train = df_train.replace(cleanup_nums)
# test = test.replace(cleanup_nums)

In [176]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115786 entries, 0 to 115785
Data columns (total 35 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   v3      115786 non-null  int64
 1   v5      115786 non-null  int64
 2   v6      115786 non-null  int64
 3   v7      115786 non-null  float64
 4   v8      115786 non-null  int64
 5   v9      115786 non-null  float64
 6   v10     115785 non-null  float64
 7   v11     93362 non-null   float64
 8   v12     93362 non-null   float64
 9   v13     93362 non-null   float64
 10  v14     93362 non-null   float64
 11  v15     115786 non-null  int64
 12  v16     115786 non-null  int64
 13  v17     115348 non-null  float64
 14  v18     115348 non-null  float64
 15  v20     115786 non-null  int64
 16  v21     115786 non-null  int64
 17  v22     115786 non-null  int64
 18  v23     115786 non-null  int64
 19  v24     115348 non-null  float64
 20  v25     115786 non-null  int64
 21  v26     115786 non-null  int64
 22  v27     115786 non-null  int64
 23  v28     115786 non-null  int64
 24  v29     115348 non-null  float64
 25  v30     115786 non-null  int64
 26  v31     115786 non-null  int64
 27  v32     83331 non-null   float64
 28  v33     83331 non-null   float64
 29  v34     83331 non-null   float64
 30  v35     83331 non-null   float64
 31  v36     83130 non-null   float64
 32  v37     115786 non-null  int64
 33  v38     115786 non-null  int64
 34  v39     115786 non-null  float64
dtypes: float64(17), int64(18)
memory usage: 30.9 MB

In [177]:
# df_train_noNullRows = df_train.dropna(how='any',axis=0)

In [182]:
# df_train_noNullRows.info()

In [183]:
# df_train_noNullRows['v37'].unique()

In [186]:
df_train_imputedValues = df_train

In [187]:
# df_train_imputedValues.info()

In [188]:
df_train_imputedValues.head()

,v3,v5,v6,v7,v8,v9,v10,v11,v12,v13,...,v30,v31,v32,v33,v34,v35,v36,v37,v38,v39
0,3048,1,49000,61.22,1016,16930.58,4.0,NaN,NaN,NaN,...,24,0,NaN,NaN,NaN,NaN,NaN,0,0,7740.0
1,3035,0,61990,78.08,1008,31564.74,3.0,NaN,NaN,NaN,...,24,0,NaN,NaN,NaN,NaN,NaN,0,0,23340.0
2,3035,0,47440,84.11,1016,28627.74,3.0,NaN,NaN,NaN,...,24,0,19135.0,27.0,38835.0,0.0,-50.0,0,0,16980.0
3,3005,1,57810,84.89,1016,49684.70,0.0,NaN,NaN,NaN,...,25,0,NaN,NaN,NaN,NaN,NaN,0,0,28920.0
4,3050,0,49000,85.20,1016,40158.23,4.0,NaN,NaN,NaN,...,37,0,NaN,NaN,NaN,NaN,NaN,0,0,21560.0

In [189]:
df_train_imputedValues = df_train_imputedValues.fillna(df_train_imputedValues["v10"].mode()[0])
# df_train_imputedValues.head()
df_train_imputedValues = df_train_imputedValues.fillna(df_train_imputedValues['v11'].mode()[0])
df_train_imputedValues = df_train_imputedValues.fillna(df_train_imputedValues['v12'].mode()[0])
df_train_imputedValues = df_train_imputedValues.fillna(df_train_imputedValues['v13'].mode()[0])
df_train_imputedValues = df_train_imputedValues.fillna(df_train_imputedValues['v14'].mode()[0])
df_train_imputedValues = df_train_imputedValues.fillna(df_train_imputedValues['v17'].mode()[0])
df_train_imputedValues = df_train_imputedValues.fillna(df_train_imputedValues['v18'].mode()[0])
df_train_imputedValues = df_train_imputedValues.fillna(df_train_imputedValues['v24'].mode()[0])
df_train_imputedValues = df_train_imputedValues.fillna(df_train_imputedValues['v32'].mode()[0])
df_train_imputedValues = df_train_imputedValues.fillna(df_train_imputedValues['v33'].mode()[0])
df_train_imputedValues = df_train_imputedValues.fillna(df_train_imputedValues['v34'].mode()[0])
df_train_imputedValues = df_train_imputedValues.fillna(df_train_imputedValues['v35'].mode()[0])
df_train_imputedValues = df_train_imputedValues.fillna(df_train_imputedValues['v36'].mode()[0])

In [190]:
df_train_imputedValues.head()

,v3,v5,v6,v7,v8,v9,v10,v11,v12,v13,...,v30,v31,v32,v33,v34,v35,v36,v37,v38,v39
0,3048,1,49000,61.22,1016,16930.58,4.0,3.0,3.0,3.0,...,24,0,3.0,3.0,3.0,3.0,3.0,0,0,7740.0
1,3035,0,61990,78.08,1008,31564.74,3.0,3.0,3.0,3.0,...,24,0,3.0,3.0,3.0,3.0,3.0,0,0,23340.0
2,3035,0,47440,84.11,1016,28627.74,3.0,3.0,3.0,3.0,...,24,0,19135.0,27.0,38835.0,0.0,-50.0,0,0,16980.0
3,3005,1,57810,84.89,1016,49684.70,0.0,3.0,3.0,3.0,...,25,0,3.0,3.0,3.0,3.0,3.0,0,0,28920.0
4,3050,0,49000,85.20,1016,40158.23,4.0,3.0,3.0,3.0,...,37,0,3.0,3.0,3.0,3.0,3.0,0,0,21560.0

In [191]:
df_train_imputedValues.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115786 entries, 0 to 115785
Data columns (total 35 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   v3      115786 non-null  int64
 1   v5      115786 non-null  int64
 2   v6      115786 non-null  int64
 3   v7      115786 non-null  float64
 4   v8      115786 non-null  int64
 5   v9      115786 non-null  float64
 6   v10     115786 non-null  float64
 7   v11     115786 non-null  float64
 8   v12     115786 non-null  float64
 9   v13     115786 non-null  float64
 10  v14     115786 non-null  float64
 11  v15     115786 non-null  int64
 12  v16     115786 non-null  int64
 13  v17     115786 non-null  float64
 14  v18     115786 non-null  float64
 15  v20     115786 non-null  int64
 16  v21     115786 non-null  int64
 17  v22     115786 non-null  int64
 18  v23     115786 non-null  int64
 19  v24     115786 non-null  float64
 20  v25     115786 non-null  int64
 21  v26     115786 non-null  int64
 22  v27     115786 non-null  int64
 23  v28     115786 non-null  int64
 24  v29     115786 non-null  float64
 25  v30     115786 non-null  int64
 26  v31     115786 non-null  int64
 27  v32     115786 non-null  float64
 28  v33     115786 non-null  float64
 29  v34     115786 non-null  float64
 30  v35     115786 non-null  float64
 31  v36     115786 non-null  float64
 32  v37     115786 non-null  int64
 33  v38     115786 non-null  int64
 34  v39     115786 non-null  float64
dtypes: float64(17), int64(18)
memory usage: 30.9 MB

In [192]:
corr=df_train_imputedValues.corr() #to find correlation
corr

,v3,v5,v6,v7,v8,v9,v10,v11,v12,v13,...,v30,v31,v32,v33,v34,v35,v36,v37,v38,v39
v3,1.000000,0.118115,0.090463,-0.178210,-0.081357,0.058783,0.118797,0.005651,-0.004704,0.005056,...,0.099334,-0.016671,-0.002629,0.010391,0.007167,0.010602,0.002271,-0.417510,0.029449,-0.180579
v5,0.118115,1.000000,-0.007905,-0.078883,0.064464,-0.000608,0.021232,-0.024246,-0.022760,-0.021133,...,-0.032473,0.010134,0.018796,0.017624,0.023775,0.002954,-0.046199,-0.123169,0.021836,-0.094608
v6,0.090463,-0.007905,1.000000,-0.222444,-0.431307,0.721679,-0.014780,-0.153868,-0.150401,-0.133964,...,0.418204,0.165547,-0.007630,-0.082184,-0.014146,0.042939,-0.018478,-0.052438,0.047706,0.667920
v7,-0.178210,-0.078883,-0.222444,1.000000,0.116711,0.095109,-0.116422,-0.067836,-0.069098,-0.070775,...,0.128389,0.084393,-0.008534,-0.074692,-0.008538,-0.019711,0.035722,0.145444,-0.025346,0.023248
v8,-0.081357,0.064464,-0.431307,0.116711,1.000000,-0.289119,-0.003872,0.055549,0.062824,0.055329,...,-0.196046,-0.066839,0.005263,0.030284,0.004509,0.025368,0.005266,0.028150,-0.017802,-0.363588
v9,0.058783,-0.000608,0.721679,0.095109,-0.289119,1.000000,0.033037,-0.044556,-0.047464,-0.034400,...,0.398822,0.126571,-0.010287,-0.098561,-0.018808,-0.034456,-0.141561,-0.076309,0.040490,0.604001
v10,0.118797,0.021232,-0.014780,-0.116422,-0.003872,0.033037,1.000000,-0.138547,-0.138821,-0.136927,...,0.014846,-0.059574,0.002348,0.057243,0.000518,0.023459,0.187918,-0.102681,0.018377,-0.182329
v11,0.005651,-0.024246,-0.153868,-0.067836,0.055549,-0.044556,-0.138547,1.000000,0.923342,0.915426,...,-0.170821,-0.245884,0.019126,0.187708,0.014609,-0.070800,-0.244006,-0.071883,-0.115977,-0.027985
v12,-0.004704,-0.022760,-0.150401,-0.069098,0.062824,-0.047464,-0.138821,0.923342,1.000000,0.933657,...,-0.162816,-0.242832,0.020431,0.188021,0.015248,-0.065503,-0.241455,-0.061859,-0.156086,-0.014001
v13,0.005056,-0.021133,-0.133964,-0.070775,0.055329,-0.034400,-0.136927,0.915426,0.933657,1.000000,...,-0.150037,-0.242273,0.020800,0.186925,0.013838,-0.066170,-0.240843,-0.068151,-0.121074,-0.014110
v14,-0.000543,-0.025720,-0.144651,-0.068071,0.058583,-0.041981,-0.140546,0.921728,0.956701,0.948485,...,-0.160426,-0.242006,0.020490,0.185992,0.014466,-0.065531,-0.242183,-0.061912,-0.149417,-0.009339
v15,-0.088536,-0.069395,0.041454,0.057726,-0.052322,-0.011398,-0.023842,-0.042042,-0.042702,-0.043248,...,0.027742,0.093575,0.000865,-0.005479,0.005439,-0.034610,-0.003927,0.117289,0.001487,0.201037
v16,-0.030365,0.000587,0.398466,0.170349,-0.185341,0.478477,-0.191257,-0.342217,-0.345025,-0.344035,...,0.162845,0.357938,-0.024091,-0.294054,-0.026846,0.019634,0.119027,0.064424,0.039758,0.487147
v17,0.052237,-0.012812,-0.061830,-0.132772,-0.000720,-0.413846,0.527768,-0.253520,-0.246517,-0.245215,...,0.236707,-0.040849,0.008655,0.076348,0.009332,0.095073,0.351981,0.021894,0.006611,-0.282070
v18,0.066591,-0.005867,-0.098386,-0.147372,0.025888,-0.427514,0.527484,-0.228121,-0.222350,-0.220495,...,0.201032,-0.069389,0.009161,0.098173,0.009592,0.092299,0.317228,-0.010352,0.010479,-0.324551
v20,0.142483,0.037506,0.057612,-0.055152,-0.046245,0.066287,0.001631,0.021560,0.019217,0.024576,...,0.024981,-0.010066,-0.013582,-0.019163,-0.008289,-0.000587,-0.001822,-0.070427,0.022439,0.019003
v21,-0.009320,-0.007179,-0.030567,0.008481,0.012741,-0.012174,-0.065058,0.027289,0.025329,0.026665,...,-0.017966,-0.016921,-0.001447,0.007947,-0.001057,-0.008468,-0.040094,0.006831,-0.001138,-0.011256
v22,0.041379,0.019196,0.362842,0.060823,-0.156201,0.207489,0.199713,-0.539122,-0.536785,-0.534358,...,0.329721,0.325983,-0.020236,-0.244321,-0.022222,0.092308,0.369332,0.033156,0.051455,0.243009
v23,0.089585,0.022597,-0.072488,-0.145940,0.048972,-0.365314,0.490442,-0.214957,-0.208496,-0.206789,...,0.191554,-0.065126,0.006188,0.082113,0.007623,0.087012,0.296319,-0.042756,0.011104,-0.333018
v24,0.068128,0.032560,-0.154188,-0.063767,0.116749,-0.055463,0.006654,0.096328,0.091324,0.093995,...,-0.148042,-0.116891,0.001140,0.089268,-0.000369,-0.008532,-0.140113,-0.144079,0.017352,-0.182982
v25,-0.032067,0.000376,0.307169,0.034750,-0.158113,0.314091,-0.126475,-0.070014,-0.076473,-0.078562,...,-0.028541,0.104508,-0.008355,-0.095353,-0.013755,-0.031931,-0.010582,0.041187,0.012611,0.346197
v26,-0.070807,-0.020340,-0.053472,0.025092,0.040670,-0.046839,0.010279,-0.009635,-0.009938,-0.014131,...,-0.022576,0.008512,0.000333,-0.002219,0.000536,0.003673,0.006195,0.085056,-0.003226,0.002093
v27,0.049211,0.030441,0.021838,-0.031696,-0.002537,0.005586,0.102012,-0.064932,-0.061828,-0.059438,...,0.070451,-0.016879,-0.002465,-0.013548,-0.003650,0.017785,0.063605,-0.047230,0.009718,-0.096051
v28,0.153628,0.017707,0.081412,-0.035899,-0.019337,0.059039,0.064365,-0.008301,-0.017959,-0.004327,...,0.116593,-0.010993,-0.009752,0.006266,-0.009166,0.019571,0.006367,-0.295112,0.036828,-0.045313
v29,0.021800,-0.002741,-0.195080,-0.195583,0.057681,-0.523276,0.507518,-0.188693,-0.184760,-0.187991,...,-0.128233,-0.093117,0.009800,0.098107,0.010851,0.072004,0.284215,0.015088,0.004295,-0.353141
v30,0.099334,-0.032473,0.418204,0.128389,-0.196046,0.398822,0.014846,-0.170821,-0.162816,-0.150037,...,1.000000,0.119401,-0.004193,-0.054054,-0.006278,0.053620,0.144067,0.003413,0.013206,0.242967
v31,-0.016671,0.010134,0.165547,0.084393,-0.066839,0.126571,-0.059574,-0.245884,-0.242832,-0.242273,...,0.119401,1.000000,-0.015836,-0.376604,-0.008805,0.135296,0.174602,0.066496,0.030731,0.182180
v32,-0.002629,0.018796,-0.007630,-0.008534,0.005263,-0.010287,0.002348,0.019126,0.020431,0.020800,...,-0.004193,-0.015836,1.000000,0.038164,0.445093,-0.029661,-0.016608,-0.002298,-0.001602,-0.009322
v33,0.010391,0.017624,-0.082184,-0.074692,0.030284,-0.098561,0.057243,0.187708,0.188021,0.186925,...,-0.054054,-0.376604,0.038164,1.000000,0.028824,-0.487197,-0.440926,-0.049382,-0.022779,-0.104565
v34,0.007167,0.023775,-0.014146,-0.008538,0.004509,-0.018808,0.000518,0.014609,0.015248,0.013838,...,-0.006278,-0.008805,0.445093,0.028824,1.000000,-0.028025,-0.020253,-0.002104,-0.003986,-0.014693
v35,0.010602,0.002954,0.042939,-0.019711,0.025368,-0.034456,0.023459,-0.070800,-0.065503,-0.066170,...,0.053620,0.135296,-0.029661,-0.487197,-0.028025,1.000000,0.177012,-0.007037,0.003040,-0.009957
v36,0.002271,-0.046199,-0.018478,0.035722,0.005266,-0.141561,0.187918,-0.244006,-0.241455,-0.240843,...,0.144067,0.174602,-0.016608,-0.440926,-0.020253,0.177012,1.000000,0.061174,0.010021,-0.077558
v37,-0.417510,-0.123169,-0.052438,0.145444,0.028150,-0.076309,-0.102681,-0.071883,-0.061859,-0.068151,...,0.003413,0.066496,-0.002298,-0.049382,-0.002104,-0.007037,0.061174,1.000000,-0.016190,0.185936
v38,0.029449,0.021836,0.047706,-0.025346,-0.017802,0.040490,0.018377,-0.115977,-0.156086,-0.121074,...,0.013206,0.030731,-0.001602,-0.022779,-0.003986,0.003040,0.010021,-0.016190,1.000000,-0.052588
v39,-0.180579,-0.094608,0.667920,0.023248,-0.363588,0.604001,-0.182329,-0.027985,-0.014001,-0.014110,...,0.242967,0.182180,-0.009322,-0.104565,-0.014693,-0.009957,-0.077558,0.185936,-0.052588,1.000000

In [193]:
# df_train_imputedValues_highCorr = df_train_imputedValues

In [194]:
# df_train_imputedValues_highCorr = df_train_imputedValues_highCorr.drop({"v38","v36","v35","v34","v28","v27","v26","v14","v13","v12","v11","v7","v5"}, axis=1)

In [195]:
# corr=df_train_noNullRows.corr() #to find correlation
# corr
# v6,v8,v9,v16 are highly correlated

In [196]:
# drop v32 , v21
# df_train_imputedValues = df_train_imputedValues.drop({"v32","v21"}, axis=1)
# df_train_noNullRows = df_train_noNullRows.drop({"v32","v21"}, axis=1)

In [197]:
# df_train_imputedValues = df_train_imputedValues.drop({"v20"}, axis=1)
# df_train_noNullRows = df_train_noNullRows.drop({"v20"}, axis=1)

In [198]:
# df_train_imputedValues.info()

In [199]:
# # f, ax = plt.subplots(figsize=(15,8))
# sns.displot(df_train_noNullRows['v8'])
# sns.displot(df_train_noNullRows['v16'])
# plt.xlim([0,160])

In [200]:
# df_train_noNullRows['avg cond'] = (df_train_noNullRows['v11'] + df_train_noNullRows['v12'] + df_train_noNullRows['v13'] + df_train_noNullRows['v14'])/4
# df_train_noNullRows = df_train_noNullRows.drop({"v11","v12","v13","v14"}, axis=1)

In [201]:
# corr=df_train_noNullRows.corr() #to find correlation
# corr

In [202]:
# Creating df of high corr values, more than 0.25
# df_train_noNullRows_high_corr = df_train_noNullRows

In [203]:
# df_train_noNullRows_high_corr = df_train_noNullRows_high_corr.drop({"v38","v35","v34","v33","v31","v28","v26","v7","v5"}, axis = 1)

In [204]:
# corr = df_train_noNullRows_high_corr.corr()

In [205]:
# corr

In [206]:
# Noramlize the data
# from sklearn.preprocessing import StandardScaler

# sc = StandardScaler()

# # get numeric data
# num_d = X_test.select_dtypes(exclude=['object'])

# # update the cols with their normalized values
# X_test[num_d.columns] = sc.fit_transform(num_d)

In [207]:
def check_skew(df):
numeric_feats = df.dtypes[df.dtypes != "object"].index

# Check the skew of all numerical features
skewed_feats = df[numeric_feats].apply(lambda x: skew(x.dropna())).sort_values(ascending=False)
print("\nSkew in numerical features: \n")
skewness = pd.DataFrame({'Skew' :skewed_feats})
print(skewness.head(15))

In [208]:
def fix_skew(df):
    from scipy.special import boxcox1p
    skewed_features = ["Air_Quality_Index","Property_Area"]
    lam = 0.15
    for feat in skewed_features:
        #all_data[feat] += 1
        df[feat] = boxcox1p(df[feat], lam)

In [209]:
# from sklearn.model_selection import train_test_split
# Y = df_train_noNullRows['v39']
# X = df_train_noNullRows.drop(columns=['v39'])
# X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.15, random_state=9)

# print('X train shape: ', X_train.shape)
# print('Y train shape: ', y_train.shape)
# print('X test shape: ', X_test.shape)
# print('Y test shape: ', y_test.shape)

# 0.69 random forest

In [210]:
# from sklearn.model_selection import train_test_split
# Y = df_train_noNullRows_high_corr['v39']
# X = df_train_noNullRows_high_corr.drop(columns=['v39'])
# X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.15, random_state=9)

# print('X train shape: ', X_train.shape)
# print('Y train shape: ', y_train.shape)
# print('X test shape: ', X_test.shape)
# print('Y test shape: ', y_test.shape)

# 0.67 accuracy on this

In [211]:
from sklearn.model_selection import train_test_split
Y = df_train_imputedValues['v39']
X = df_train_imputedValues.drop(columns=['v39'])
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.15, random_state=9)

print('X train shape: ', X_train.shape)
print('Y train shape: ', y_train.shape)
print('X test shape: ', X_test.shape)
print('Y test shape: ', y_test.shape)

# 0.77 on random forest

X train shape:  (98418, 34)
Y train shape:  (98418,)
X test shape:  (17368, 34)
Y test shape:  (17368,)

In [212]:
# from sklearn.model_selection import train_test_split
# Y = df_train_imputedValues_highCorr['v39']
# X = df_train_imputedValues_highCorr.drop(columns=['v39'])
# X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.15, random_state=9)

# print('X train shape: ', X_train.shape)
# print('Y train shape: ', y_train.shape)
# print('X test shape: ', X_test.shape)
# print('Y test shape: ', y_test.shape)

# 0.67

In [213]:
# Random forest
from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor()
rf_reg.fit(X_train, y_train)
y_pred= rf_reg.predict(X_test)
print("Accuracy on Traing set: ",rf_reg.score(X_train,y_train))
print("Accuracy on Testing set: ",rf_reg.score(X_test,y_test))

Accuracy on Traing set:  0.9685999212998765
Accuracy on Testing set:  0.7721756198457643

In [214]:
from sklearn import metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error

print("\t\tError Table")
print('Mean Absolute Error      : ', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared  Error      : ', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared  Error : ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('R Squared Error          : ', metrics.r2_score(y_test, y_pred))

		Error Table
Mean Absolute Error      :  4230.918001958199
Mean Squared  Error      :  34029493.02610524
Root Mean Squared  Error :  5833.480352765855
R Squared Error          :  0.7721756198457643

In [215]:
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.metrics import r2_score,mean_squared_error
# from sklearn.metrics import mean_absolute_error 
# from sklearn.model_selection import cross_val_score, GridSearchCV
# # We define the model
# estimator = RandomForestRegressor(random_state = 42,criterion='mse')
# para_grids = {
#             "n_estimators" : [10,50,100],
#             "max_features" : ["auto", "log2", "sqrt"],
#             'max_depth' : [4,5,6,7,8,9,15],
#             "bootstrap"    : [True, False]
#         }


# Grid = GridSearchCV(estimator, para_grids,cv= 5)
# # We train model
# Grid.fit(X_train, y_train)
# best_param = Grid.best_estimator_
# print(best_param)

In [216]:
# Y_predict = best_param.predict(X_test)
# Y_predict

In [217]:
from xgboost import XGBRegressor
xgb = XGBRegressor()
xgb.fit(X_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, ...)

In [218]:
y_pred=xgb.predict(X_test)

In [219]:
# tsc5=regressor.score(X_train,y_train)
# tsc5

In [220]:
from sklearn import metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error

print("\t\tError Table")
print('Mean Absolute Error      : ', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared  Error      : ', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared  Error : ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('R Squared Error          : ', metrics.r2_score(y_test, y_pred))

		Error Table
Mean Absolute Error      :  4124.744196677764
Mean Squared  Error      :  31987649.054318342
Root Mean Squared  Error :  5655.762464453253
R Squared Error          :  0.7858455806908217

In [ ]:
estimators = [ ('elastic_net', elastic_net), ('kernel_ridge', kernel_ridge),('xgb_regressor', xgb_regressor) ]

stack = StackingRegressor(estimators=estimators, final_estimator= lasso, cv= 5, n_jobs= n_jobs, passthrough = True)

stack.fit(X_train, y_train)

pred = stack.predict(X_test)

rmse_val = mean_squared_error(y_test, pred, squared= False) # squared= False > returns Root Mean Square Error    
models_scores.append(['Stacking', rmse_val])
print(f'rmse= {rmse_val}')

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

# model_KNN=KNeighborsRegressor(n_neighbors=4, metric='euclidean')
model_KNN=KNeighborsRegressor()
model_KNN.fit(X_train,y_train)

In [ ]:
from sklearn.ensemble import AdaBoostRegressor

# adaboost_regressor = AdaBoostRegressor(n_estimators=1500, learning_rate = 0.001, loss='exponential')
adaboost_regressor = AdaBoostRegressor()
ada_model = adaboost_regressor.fit(X_train, y_train)
prediction_test_ada = ada_model.predict(X_test)

In [ ]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
# from xgboost import XGBClassifier

parameters = {'nthread':[4], #when use hyperthread, xgboost may become slower
              'objective':['reg:linear'],
              'learning_rate': [.1, 0.09, .07], #so called `eta` value
              'max_depth': [9, 7, 14],
              'min_child_weight': [1,4,8],
              'silent': [1],
              'subsample': [0.7,1,0.5],
              'colsample_bytree': [0.7,1,0.5],
              'n_estimators': [800]}

xgb_grid = GridSearchCV(xgb,
                        parameters,
                        cv = 2,
                        n_jobs = 5,
                        verbose=True)

xgb_grid.fit(X_train,
         y_train)

print(xgb_grid.best_score_)
print(xgb_grid.best_params_)

In [ ]:
estimators = [ ('random forest', rf_reg), ('ridge regression', ridge_reg), ('lasso regression'), lasso_reg]

stack = StackingRegressor(estimators=estimators, final_estimator= xgb, cv= 5, n_jobs= n_jobs, passthrough = True)

stack.fit(X_train, y_train)

y_pred4 = stack.predict(X_test)

# rmse_val = mean_squared_error(y_test, pred, squared= False) # squared= False > returns Root Mean Square Error    
# models_scores.append(['Stacking', rmse_val])
# print(f'rmse= {rmse_val}')
print('R Squared Error          : ', metrics.r2_score(y_test, y_pred4))